### PR TITLE
Run length

### PR DESCRIPTION
**Pull request by CorneliaKelinske**
This is how far I have come with my decode function.
If you could have a look, thank you!

### CODE REVIEW

**Comment by alanvardy** [comment]
Check out this Regex: https://regex101.com/r/1MZwD5/1

I think you can use it with `Regex.scan/2`

**Comment by CorneliaKelinske** [comment]
Thank you! I will check it out!

**Comment by CorneliaKelinske** [comment]
I am now at a point where the tests for decoding pass, unless there are whitespaces involved.
I'd appreaciate it if you could look at what I have done thus far and let me know if you see something fundamentally wrong with my general approach, or if there is a solution for the whitespace problem.

If so, a hint as to what direction I should go in would be cool.
Thank you!

**Comment by alanvardy** [comment]
> I am now at a point where the tests for decoding pass, unless there are whitespaces involved.
> I'd appreaciate it if you could look at what I have done thus far and let me know if you see something fundamentally wrong with my general approach, or if there is a solution for the whitespace problem.
> 
> If so, a hint as to what direction I should go in would be cool.
> Thank you!

I think your implementation is good, I just think that you need to treat whitespace the same as a letter in order to get this to work. Right now the regex only handles letters and I think that a little regex modification is all you may need :+1:

**Comment by CorneliaKelinske** [comment]
@alanvardy It is working now and ready for the final code review. If you would be so kind :)

**Review by alanvardy — APPROVED** [review]
I have nothing to add, it looks great.

**Pull request merged**
